inquiry/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path("", views.inquiry, name="inquiry"), #문의하기
    path("ask", views.ask, name="ask"), #문의 글 작성 페이지
    path("inqdetail/<str:id>", views.inqdetail, name="inqdetail"), #문의 글 자세히 보기 페이지
    path("inqedit/<str:id>", views.inqedit, name="inqedit"), #문의 글 수정 페이지
    path("inqdelete/<str:id>", views.inqdelete, name="inqdelete"), #문의 글 삭제 url
    path("answer", views.answer, name="answer"), #관리자용 문의 리스트 페이지
    path("ansdetail/<str:id>", views.ansdetail, name="ansdetail"), #관리자용 문의 답변 페이지
] 

join/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path("mypage/", views.mypage, name="mypage"),
    path("sign_in/", views.sign_in, name="sign_in"),
    path("sign_up/", views.sign_up, name="sign_up"),
    path("sign_out/", views.sign_out, name="sign_out"),
] 

main/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path("", views.main, name="main"),
    path("noticeBase", views.noticeBase, name="noticeBase")
]

vote/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path("", views.vote, name="vote"),
]

category/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.db.models.base import Model
from datetime import date, timedelta
from django.conf import settings
from join.choices import *
import django_filters

# Create your models here.

#대여 기능 : ManyToManyField 사용 -> CustomUser와 외래키로 연결
from join.models import CustomUser

#기본적인 책 정보 
class BookClassInfo(models.Model):
    title = models.CharField("책제목", max_length=45)
    image = models.ImageField("책표지", blank=True,null=True)
    author = models.CharField("저자", max_length=45)
    price = models.IntegerField("가격",null=True)
    publisher = models.CharField("출판사", max_length=45)
    pubdate = models.DateField("출판일",null=True)
    stock = models.SmallIntegerField("재고", default=5)
    department = models.CharField("수업개설학과", max_length=30)
    class_name = models.CharField("수업명", max_length=30)
    professor = models.CharField("교수", max_length=30)
    # semester = models.CharField("개설학기", max_length=30,null=True)
    # class_code = models.CharField("과목코드", max_length=7,null=True)

    #detail models
    borrows = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name = 'borrow')
    wishes = models.ManyToManyField(settings.AUTH_USER_MODEL,blank=True, related_name = 'wish')
    
    class Meta:
        ordering = ['title']

    def __str__(self):
        return "{} - {}".format(self.title,self.class_name)


#물리적인 책 각각의 상태
class BookWhere(models.Model):
    STATUS = [
        ('보관','보관'),
        ('대출','대출')
    ]
    book_status = models.CharField(choices=STATUS, max_length=5)
    book_info_id = models.ForeignKey(BookClassInfo, on_delete=models.CASCADE) #ManyToOne

    #대출
    def rent_book(self, user): #매개변수
        rent_start = date.today()
        rent_end = date.today() - timedelta(month=3)
        rent_info = self.UserBook_set.create(user=user, rent_start=rent_start,rent_end=rent_end,return_status=False)
        self.rent_info=rent_info
        self.save()

    #반납
    def return_book(self):
        self.rent_info.return_status=True
        self.rent_info.return_date = date.today()
        self.rent_info.save()
        self.rent_info=None
        self.save()

    def check_overdue(self):
        return self.rent_info.rent_end < date.today()

#유저가 빌린 책 
class UserBook(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='대출회원')
    book = models.ManyToManyField(BookClassInfo)
    rent_start = models.DateField("대출일")
    rent_end = models.DateField("실제 반납일")
    return_status = models.BooleanField("반납여부")
    return_date = models.DateField("반납일", blank=True, null=True)
    #sent_overdue_email = models.BooleanField("연체알림여부", default=False)

    def __str__(self):
        return "{} - {}".format(self.user,self.book)

    @property #Get,set 대신 사용
    def check_overdue(self):
        return self.rent_end < date.today() #연체될 시

    @classmethod #연체할시 1일씩 증가 
    def get_overdue_dates(cls): #클래스의 매개변수
        return cls.objects.filter(rent_end=date.today()+timedelta(days=1))

    # class Meta:
    #     ordering = ['-rent_start']

inquiry/models.py
from django.db import models

# Create your models here.

#inquiry CRUD model : register ask
class QInquiry(models.Model):
    #인적사항
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField(max_length=100)
    #문의 내용
    qtype = models.ManyToManyField('Qtype', blank=False)
    title = models.CharField(max_length=200)
    body = models.TextField()
    #기타
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.title

class Qtype(models.Model):
    type = models.CharField(max_length=50)

    def __str__(self):
        return self.type

#inquiry Comment model : admin answer
class Answer(models.Model):
    def __str__(self):
        return self.text

    ask_id = models.ForeignKey(QInquiry, on_delete=models.CASCADE, related_name='answer')
    text = models.TextField()

main/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.db.models.base import Model
from datetime import date, timedelta
from django.conf import settings
from join.choices import *

# Create your models here.

#기본적인 책 정보 
class BookClassInfo(models.Model):
    title = models.CharField("책제목", max_length=45)
    image = models.ImageField("책표지", blank=True,null=True)
    author = models.CharField("저자", max_length=45)
    price = models.IntegerField("가격",null=True)
    publisher = models.CharField("출판사", max_length=45)
    pubdate = models.DateField("출판일",null=True)
    stock = models.SmallIntegerField("재고", default=5)
    department = models.CharField("수업개설학과", max_length=30)
    class_name = models.CharField("수업명", max_length=30)
    professor = models.CharField("교수", max_length=30)
    # semester = models.CharField("개설학기", max_length=30,null=True)
    # class_code = models.CharField("과목코드", max_length=7,null=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return "{} - {}".format(self.title,self.class_name)

#물리적인 책 각각의 상태
class BookWhere(models.Model):
    STATUS = [
        ('보관','보관'),
        ('대출','대출')
    ]
    book_status = models.CharField(choices=STATUS, max_length=5)
    book_info_id = models.ForeignKey(BookClassInfo, on_delete=models.CASCADE) #ManyToOne

    #대출
    def rent_book(self, user): #매개변수
        rent_start = date.today()
        rent_end = date.today() - timedelta(month=3)
        rent_info = self.UserBook_set.create(user=user, rent_start=rent_start,rent_end=rent_end,return_status=False)
        self.rent_info=rent_info
        self.save()

    #반납
    def return_book(self):
        self.rent_info.return_status=True
        self.rent_info.return_date = date.today()
        self.rent_info.save()
        self.rent_info=None
        self.save()

    def check_overdue(self):
        return self.rent_info.rent_end < date.today()

vote/models.py
from django.db import models

# Create your models here.

inquiry/forms.py
from django import forms
from django.db.models import fields
from .models import *

#문의 글 작성 폼
class QInquiryForm(forms.ModelForm):
    class Meta:
        model = QInquiry
        fields = ['title', 'body']
#  'qtype', 
#관리자용 해시태그 추가 폼
class QtypeForm(forms.ModelForm):
    class Meta:
        model = Qtype
        fields = ['type']

#관리자용 문의 답변 작성 폼
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['text']

category/views.py
from django.core import paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.http.response import HttpResponse
from .models import BookClassInfo
from join.models import CustomUser
from django.core.paginator import Paginator

# 검색과 페이징
def category(request):
    
    books = BookClassInfo.objects.all()
    search = request.GET.get('search', '')
    sort_val = books

    if search:
        books = books.filter(title__icontains=search)
        sort_val = books

    major = request.GET.get('major', '')
    if major == "인문":
        major_list = BookClassInfo.objects.filter(department='인문융합자율학부')
        sort_val = major_list
    if major == "사회":
        major_list = BookClassInfo.objects.filter(department='사회융합자율학부')
        sort_val = major_list
    if major == "미컨":
        major_list = BookClassInfo.objects.filter(department='미디어콘텐츠융합자율학부')
        sort_val = major_list
    if major == "IT":
        major_list = BookClassInfo.objects.filter(department='IT융합자율학부')
        sort_val = major_list

    paginator = Paginator(sort_val, 9)
    page = request.GET.get('page', '') #몇번째 페이지인지 받아옴
    book_list = paginator.get_page(page) #posts


    return render(request, 'category.html', {'book_list':book_list, 'search':search, 'major':major})
    
#detail 페이지 구현
#detail page
def detail(request, id):
    book = get_object_or_404(BookClassInfo, id = id)
    return render(request, 'detail.html', {'book':book})

#borrow 기능
def borrow(request, id):
    if not request.user.is_active:
        return HttpResponse('로그인 해주세요')
    
    book = get_object_or_404(BookClassInfo, id = id)
    user = request.user

    if book.borrows.filter(id = user.id).exists():
        book.borrows.remove(user)
        book.stock += 1
        book.save()

    else:
        book.borrows.add(user)
        book.stock -= 1
        book.save()
        
        if book.stock == 0:
            return HttpResponse('재고가 없습니다.')
    return redirect('detail', id = book.id)

#찜하기
def wish(request, id):
    if not request.user.is_active:
        return HttpResponse('로그인 해주세요')
    
    book = get_object_or_404(BookClassInfo, id = id)
    user = request.user

    if book.wishes.filter(id = user.id).exists():
        book.wishes.remove(user)

    else:
        book.wishes.add(user)

    return redirect('detail', id = book.id)

inquiry/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from .models import *
from .forms import *
from django.http import HttpResponse
# Create your views here.

#views for register

#문의 목록 페이지
def inquiry(request):
    inquirys = QInquiry.objects
    return render(request, 'inquiry.html', {'inquirys':inquirys})

#문의 글 작성 페이지
def ask(request):
    if request.method == 'POST':
        form = QInquiryForm(request.POST)
        if form.is_valid():
            inquiry = form.save(commit=False)
            inquiry.pub_date = timezone.now()
            inquiry.save()
            form.save_m2m()
            return redirect('inquiry')
    else:
        form = QInquiryForm()
        return render(request, 'ask.html', {'form' : form})
    
#작성 글 자세히 보기
def inqdetail(request, id):
    inquiry = get_object_or_404(QInquiry, id = id)
    return render(request, 'inqdetail.html', {'inquiry':inquiry})

#작성 글 수정하기
def inqedit(request, id):
    inquiry = get_object_or_404(QInquiry, id = id)
    if request.method == 'POST':
        form = QInquiryForm(request.POST, instance=inquiry)
        if form.is_valid():
            inquiry = form.save(commit=False)
            inquiry.pub_date = timezone.now()
            inquiry.save()
            form.save_m2m()
            return redirect('inqdetail', id)
    else:
        form = QInquiryForm(instance=inquiry)
        return render(request, 'inqedit.html', {'form' : form})

#작성 글 삭제하기
def inqdelete(request, id):
    inquiry = get_object_or_404(QInquiry, id = id)
    inquiry.delete()
    return redirect('inquiry')

#views for admin

#관리자용 문의글 목록 페이지
def answer(request):
    inquirys = QInquiry.objects
    return render(request, 'answer.html', {'inquirys':inquirys})

#관리자용 문의 답변 페이지
def ansdetail(request, id):
    inquiry = get_object_or_404(QInquiry, id = id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit = False)
            answer.ask_id = inquiry
            answer.text = form.cleaned_data['text']
            answer.save()
            return redirect('ansdetail', id)

    else:
        form = AnswerForm()
        return render(request, 'ansdetail.html', {'inquiry':inquiry, 'form':form})

main/views.py
from django.core import paginator
from django.shortcuts import render,get_object_or_404
from category.models import BookClassInfo
from django.core.paginator import Paginator
import random
# Create your views here.


def main(request):
    books = BookClassInfo.objects.all()
    sort_val = books

    ranNum = random.randrange(0, 4)
    if ranNum == 0:
        major_list = BookClassInfo.objects.filter(department='인문융합자율학부')
        major = "인문융합자율학부"
        sort_val = major_list
    if ranNum == 1:
        major_list = BookClassInfo.objects.filter(department='사회융합자율학부')
        major="사회융합자율학부"
        sort_val = major_list
    if ranNum == 2:
        major_list = BookClassInfo.objects.filter(department='미디어콘텐츠융합자율학부')
        major="미디어콘텐츠융합자율학부"
        sort_val = major_list
    if ranNum == 3:
        major_list = BookClassInfo.objects.filter(department='IT융합자율학부')
        major="IT융합자율학부"
        sort_val = major_list

    paginator = Paginator(sort_val, 8)
    book_list = paginator.get_page(1)  # posts

    return render(request, 'main.html', {'book_list': book_list, 'major': major})


def noticeBase(request):
    return render(request, 'noticeBase.html')


def detail(request, id):
    book = get_object_or_404(BookClassInfo, id = id)
    return render(request, 'detail.html', {'book':book})

vote/views.py
from django.shortcuts import render

# Create your views here.
def vote(request):
    return render(request, 'vote.html')

templates/ansdetail.html
<h1>admin : inquiry answer 페이지</h1>
<hr>
<h2>{{inquiry.title}}</h2>
<p>작성자 : <b>{{inquiry.last_name}} {{inquiry.first_name}}</b></p>
<p>작성자 전화번호 : <b>{{inquiry.phone_number}}</b></p>
<p>작성자 이메일 : <b>{{inquiry.email}}</b></p>
<br>
<p>작성 시간 : {{inquiry.pub_date}}</p>
{% for qtype in inquiry.qtype.all %}
<p>문의 유형 : {{qtype.type}}</p>
{% endfor %}
<p>작성 내용 : {{inquiry.body}}</p>
<a href="{% url 'inqdelete' inquiry.id %}">삭제하기</a>
<hr>
{% for answer in inquiry.answer.all %}
<p>{{answer.text}}</p>
{% endfor %}
<form method="POST">
    {% csrf_token %}
    <p>{{form.as_p}}</p>
    <input type="submit" value="답변작성">
</form>

templates/answer.html
<h1>admin : inquiry list 페이지</h1>
{% for inquiry in inquirys.all %}
<p>문의 유형 : {{qtype.type}}</p>
<p>{{inquiry.id}}.</p>
<p><a href="{% url 'ansdetail' inquiry.id %}">{{inquiry.title}}</a></p>
<p>{{inquiry.pub_date}}</p>
<p>작성자 : <b>{{inquiry.last_name}} {{inquiry.first_name}}</b></p>
<br>
<p>작성 시간 : {{inquiry.pub_date}}</p>
{% endfor %}

templates/ask.html
{% extends 'base.html' %} {% load static %} {% block content %}

<link rel="stylesheet" href="{% static 'css/noticeBase.css'%}" />
<link rel="stylesheet" href="{% static 'css/inquiry.css'%}" />
<div class="noticeTitle">
  <h2>Inquiry</h2>
</div>

<div class="noticeTool">
  <div class="noticeTool__category">
    <div class="noticeTool__category__title">BOOKREST 문의하기</div>
    <div class="noticeTool__category__link">
      <a
      class="js-inquiryListA js-noticeTool__category__link"
      href="{% url 'inquiry' %}"
      >내 문의 목록</a
    >
      <a
        class="js-inquiryA js-noticeTool__category__link"
        href="{% url 'ask' %}"
        >문의하기</a
      >
    </div>
  </div>

  <div class="noticeTool__summaryBigTool">
      <div class="noticeTool__summaryTool">
        <div class="noticeTool__summaryTool__box js-inquiry noticeShowing">
          <div class="noticeTool__summaryTool__box__title">
            <h1>문의하기</h1>
          </div>
          <div class="noticeTool__summaryTool__box__summary">
            <form method="POST">
              {% csrf_token %}<b>제목</b>
              <input
                type="text"
                class="noticeTool__summaryTool__box__summary__inquirytitle"
                id="id_title"
                name="title"
              />

              <b>문의 유형</b>
              <select
                name="qtype"
                required=""
                id="id_qtype"
                class="noticeTool__summaryTool__box__summary__select"
              >

                <option value="" style="text-align: center">
                  --문의 유형을 선택해주세요--
                </option>
                <option>반납</option>
                <option>대여</option>
                <option>연체</option>
                <option>분실</option>
                <option>훼손</option>
                <option>이외 기타</option>
              </select>

              <b>내용</b>
              <textarea
                rows="6"
                cols="40"
                class="noticeTool__summaryTool__box__summary__textarea"
                id="id_body"
                name="body"
              ></textarea>
              <p class="noticeTool__summaryTool__box__summary__p">
                BOOKREST에 대해 궁금한 점이나, 이야기 할 사항이 있으시다면 글을 남겨주세요. 빠르게 답변 드리겠습니다. 
                ※ 답변은 댓글로 확인 가능합니다. 급한 사항일 경우 010-4072-1062로 연락바랍니다.
              </p>

              <button
                type="submit"
                class="noticeTool__summaryTool__box__summary__button"
              >제출하기
              </button>
            </form>
          </div>
        </div>
      </div>
    
  </div>
</div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image⁄x-icon" href="{% static 'img/logo.png'%}" />
    <link rel="stylesheet" href="{% static 'css/base.css'%}"">
    <title>BOOKREST</title>
  </head>
  <body>
    <div class="nav">
      <div class="nav__logo">
        <h1>
          <a href="{% url 'main' %}">BOOKREST</a>
        </h1>
      </div>

      <div class="nav__menu">
        <a
          class="nav__menu__link js-nav__menu__link"
          href="{% url 'noticeBase' %}"
          data-path="/noticeBase"
          >공지사항</a
        >
        <a
          class="nav__menu__link js-nav__menu__link"
          href="{% url 'category' %}"
          data-path="/category/"
          >카테고리</a
        >
        <a
          class="nav__menu__link js-nav__menu__link"
          href="{% url 'vote' %}"
          data-path="/vote/"
          >이달의 책</a
        >
        <a
          class="nav__menu__link js-nav__menu__link"
          href="{% url 'inquiry' %}"
          data-path="/inquiry/"
          >문의하기</a
        >
        {% if user.is_active %}
        <a
          class="nav__menu__link js-nav__menu__link"
          href="{% url 'sign_out' %}"
          >로그아웃</a
        >
        <a
          class="nav__menu__link js-nav__menu__link"
          href="{% url 'mypage' %}"
          data-path="/join/mypage/"
          >{{ user.username }}님 안녕하세요.</a
        >
        {% else %}
        <a
          class="nav__menu__link js-nav__menu__link"
          href="{% url 'sign_up' %}"
          data-path="/join/sign_up/"
          >회원가입</a
        >
        <a
          class="nav__menu__link js-nav__menu__link"
          href="{% url 'sign_in' %}"
          data-path="/join/sign_in/"
          >로그인</a
        >
        {% endif %}
      </div>
    </div>

    {% block content %} {% endblock %}

    <script src="{% static 'js/nav.js'%}"></script>
  </body>
</html>

templates/category.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}
<link rel="stylesheet" href="{% static 'css/category.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>


<div class="background">
    <div class="category">
        <form method="GET" action="{% url 'category' %}">

        <div class="category_nav">
            <div class="item" id="all"><button id="get_all">전체보기</button></div>
            <div class="item" id="humanities"><button id="get_humanities" name="major" value="인문">인문</button></div>
            <div class="item" id="society"><button id="get_society" name="major" value="사회">사회</button></div>
            <div class="item" id="media_content"><button id="get_media_content" name="major" value="미컨">미컨</button></div>
            <div class="item" id="it"><button id="get_it" name="major" value="IT">IT</button></div>
        </div>    
        
            <div class="category_search">
                <div class="text_item"><input type="text" placeholder="책 제목을 입력하세요." name="search" value="{{search}}"></div>
                <div class="button_item"><button>검색</button></div>
            </div>
        </form>

        <div class="book_list">
            {% for book in book_list %}
            
            <div class="book">
                <a class="link" href="{% url 'detail' book.id %}">

                
                <div class="title" id="title" name="title">
                    <h2 >{{ book.title }}</h2>
                    
                </div>
                <div class="book_middle">
                    <hr>
                <div class="book_card">
                    <div class="img_area">
                    {% if book.image %}
                    <img src="{{ book.image }}" alt=""/>
                    {% endif %}
                    </div>
                    <div class="book_card_column">
                        <span class="book_category">
                            <h4 class="column_title">카테고리</h4>
                            <br><p class="department">{{ book.department }}</p>
                        </span>
                        <span class="book_author"><h4 class="column_title">저자</h4>&ensp;{{ book.author }}
                        </span>
                        <span class="book_publisher">
                            <h4 class="column_title">출판사</h4>&ensp;{{ book.publisher }}
                        </span>
                        <span class="book_date">
                            <h4 class="column_title">출간일</h4>&ensp;{{ book.pubdate }}
                        </span class="book_left">
                        <span class="book_date">
                            <h4 class="column_title">재고</h4>&ensp;{{ book.stock }}
                        </span class="book_left">
                    </div>
                </div>
                </div>
                

            </a>
            </div>
            
            {% endfor %}

        </div>
        
        <div class="page">
            {% if book_list.has_previous %}
            <a href='?page={{book_list.previous_page_number}}&search={{search}}&major={{major}}' class="page_move">이전</a>
          {% endif %}
            <span>{{book_list.number}}</span>
            <span>&ensp;/&ensp;</span>
            <span>{{book_list.paginator.num_pages}}</span>
          {% if book_list.has_next %}
            <a href='?page={{book_list.next_page_number}}&search={{search}}&major={{major}}' class="page_move">다음</a>
          {% endif %}
        </div>
    
    
    </div>
</div>
    <!--js 불러오기-->
    <script src="{% static 'js/category.js '%}"></script>
    <script src="{% static 'js/star.js '%}"></script>
    
{% endblock %}

templates/inqdetail.html
{% extends 'base.html' %} {% load static %} {% block content %}

<link rel="stylesheet" href="{% static 'css/noticeBase.css'%}" />
<link rel="stylesheet" href="{% static 'css/inquiry.css'%}" />
<link rel="stylesheet" href="{% static 'css/inqdetail.css'%}" />

<div class="noticeTitle">
  <h2>Inquiry</h2>
</div>
<div class="inquiry__editTool__Big">
<div class="inquiry__editTool">
<h2>{{inquiry.title}}</h2>
<!-- <p>작성자 : <b>{{inquiry.last_name}} {{inquiry.first_name}}</b></p> -->
<p>작성 시간 : {{inquiry.pub_date}}</p>
{% for qtype in inquiry.qtype.all %}
<p>문의 유형 : {{qtype.type}}</p>
{% endfor %}
<p>작성 내용 : {{inquiry.body}}</p>
<div class="editDelete__button">
<a href="{% url 'inqedit' inquiry.id %}">수정하기</a>
<a href="{% url 'inqdelete' inquiry.id %}">삭제하기</a>
</div>
<hr>
{% for answer in inquiry.answer.all %}
<h3><mark>관리자 답변</mark></h3>
<p>{{answer.text}}</p>
{% endfor %}

</div>
</div>
{% endblock %}

templates/inqedit.html
{% extends 'base.html' %} {% load static %} {% block content %}

<link rel="stylesheet" href="{% static 'css/noticeBase.css'%}" />
<link rel="stylesheet" href="{% static 'css/inquiry.css'%}" />
<div class="noticeTitle">
  <h2>Inquiry</h2>
</div>
<form method="POST">
    
  <div class="noticeTool__summaryBigTool">
    <div class="noticeTool__summaryTool">
      <div class="noticeTool__summaryTool__box js-inquiry noticeShowing">
        <div class="noticeTool__summaryTool__box__title">
          <h1>문의하기 수정</h1>
        </div>
        <div class="noticeTool__summaryTool__box__summary">
          <form method="POST">
            {% csrf_token %}<b>제목</b>
            <input
              type="text"
              class="noticeTool__summaryTool__box__summary__inquirytitle"
              id="id_title"
              name="title"
            />

            <b>문의 유형</b>
            <select
              name="qtype"
              required=""
              id="id_qtype"
              class="noticeTool__summaryTool__box__summary__select"
            >

              <option value="" style="text-align: center">
                --문의 유형을 선택해주세요--
              </option>
              <option>반납</option>
              <option>대여</option>
              <option>연체</option>
              <option>분실</option>
              <option>훼손</option>
              <option>이외 기타</option>
            </select>

            <b>내용</b>
            <textarea
              rows="6"
              cols="40"
              class="noticeTool__summaryTool__box__summary__textarea"
              id="id_body"
              name="body"
            ></textarea>
          

            <button
              type="submit"
              class="noticeTool__summaryTool__box__summary__button"
            >수정하기
            </button>
          </form>
        </div>
      </div>
    </div>
  
</div>
</form>


{% endblock %}

templates/inquiry.html
{% extends 'base.html' %} {% load static %} {% block content %}

<link rel="stylesheet" href="{% static 'css/noticeBase.css'%}" />
<link rel="stylesheet" href="{% static 'css/inquiry.css'%}" />
<div class="noticeTitle">
  <h2>Inquiry</h2>
</div>

<div class="noticeTool">
  <div class="noticeTool__category">
    <div class="noticeTool__category__title">BOOKREST 문의하기</div>
    <div class="noticeTool__category__link">
      <a
      class="js-inquiryListA js-noticeTool__category__link"
      href="{% url 'inquiry' %}"
      >내 문의 목록</a
    >
      <a
        class="js-inquiryA js-noticeTool__category__link"
        href="{% url 'ask' %}"
        >문의하기</a
      >
    </div>
  </div>
  <div class="noticeTool__summaryBigTool">
    <div class="noticeTool__summaryTool">
      <div class="noticeTool__summaryTool__box js-inquiryList noticeShowing">
        <div class="noticeTool__summaryTool__box__title">
          <h1>내 문의 목록</h1>
        </div>
        <div class="noticeTool__summaryTool__box__summary">
          <span class="noticeTool__summaryTool__box__summary__span">전체</span>
          {% for inquiry in inquirys.all %}
          <div class="noticeTool__summaryTool__box__summary__post">
            <a href="{% url 'inqdetail' inquiry.id %}">  <div class="noticeTool__summaryTool__box__summary__post__preview">{{inquiry.title}} <span class="inquiry_pubdate">{{inquiry.pub_date}}</span>
              </div>
            </a>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}